import { randomBytes } from "node:crypto";
import { access, chmod, stat, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

export type InitOptions = {
  envPath?: string;
  allowedRoots?: string[];
  force?: boolean;
};

export async function initEnv(options: InitOptions = {}): Promise<{ path: string; created: boolean; token: string }> {
  const envPath = resolve(options.envPath ?? ".env");
  const token = randomBytes(32).toString("hex");
  const allowedRoots = options.allowedRoots?.length ? options.allowedRoots : [process.cwd()];

  if (!options.force && (await exists(envPath))) {
    return { path: envPath, created: false, token: "" };
  }

  const content = [
    "# Generated by opencode-chatgpt-bridge init",
    "OPENCODE_BRIDGE_HOST=127.0.0.1",
    "OPENCODE_BRIDGE_PORT=8787",
 "OPENCODE_BRIDGE_AUTO_PORT=true",
 "OPENCODE_BRIDGE_ALLOWED_HOSTS=127.0.0.1,localhost,hashimotoyugamac-mini.tailf9f6e3.ts.net",
    `OPENCODE_BRIDGE_TOKEN=${token}`,
    `OPENCODE_BRIDGE_ALLOWED_ROOTS=${allowedRoots.map((root) => resolve(root)).join(":")}`,
    "OPENCODE_BIN=opencode",
    "OPENCODE_BRIDGE_OPENCODE_HOST=127.0.0.1",
    "OPENCODE_BRIDGE_OPENCODE_PORT_START=4096",
    "OPENCODE_BRIDGE_TUNNEL=tailscale",
 "TAILSCALE_BIN=/Applications/Tailscale.app/Contents/MacOS/Tailscale",
    "CLOUDFLARED_BIN=cloudflared",
    "",
    "# Optional: connect to an already-running opencode server instead of spawning one per repo.",
    "# OPENCODE_BASE_URL=http://127.0.0.1:4096",
    "# OPENCODE_SERVER_USERNAME=opencode",
    "# OPENCODE_SERVER_PASSWORD=",
    ""
  ].join("\n");

  await writeFile(envPath, content, { encoding: "utf8", mode: 0o600 });
  await chmod(envPath, 0o600);
  return { path: envPath, created: true, token };
}

export type EnvFileModeReport = {
  path: string;
  exists: boolean;
  mode?: number;
  ok: boolean;
};

/**
 * Read-only permission audit for the local token file. Never modifies the file.
 * Secrets live in this file, so it must stay owner-only (0600).
 */
export async function checkEnvFileMode(envPath = ".env"): Promise<EnvFileModeReport> {
  const path = resolve(envPath);
  const info = await stat(path).catch(() => null);
  if (!info) return { path, exists: false, ok: true };
  const mode = info.mode & 0o777;
  return { path, exists: true, mode, ok: (mode & 0o077) === 0 };
}

async function exists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}
